### ISSUE TITLE
problem with Symfony 2.6.x

### ISSUE THREAD

**Issue by craigh** [schmittjoh/JMSI18nRoutingBundle#141]
please see the description here:
https://github.com/symfony/symfony/issues/12941#issuecomment-66872843

**Comment by stof** [comment]
@schmittjoh as of 2.6, there is https://github.com/symfony/symfony/blob/2.7/src/Symfony/Component/Translation/TranslatorBagInterface.php which is implemented by the Translator and could be used for that

**Comment by cmfcmf** [comment]
Turns out the LoggingTranslator does not implement the interface: https://github.com/symfony/symfony/issues/13632.
