### ISSUE TITLE
i18n_prefix option is documented but not actually in 1.0 release

### ISSUE THREAD

**Issue by mcwebb** [schmittjoh/JMSI18nRoutingBundle#169]
Just to save anyone frustration, while the i18n_prefix is documented in the 1.0 release it was only added a few months after the 1.1.1 build was released. As such, the only way to use this option is to use the master branch.

**Comment by acasademont** [comment]
A 2.0 tag will be released asap :)

**Comment by acasademont** [comment]
done!

**Comment by mcwebb** [comment]
:+1:
