### ISSUE TITLE
Extract routing based on annotations

### ISSUE THREAD

**Issue by picks44** [schmittjoh/JMSI18nRoutingBundle#170]
How can we extract the routing based on annotations ?
I tried to extract like the doc says, but I'm not getting anything.

**Comment by stof** [comment]
This bundle does not extract routing. Loading routes is done with the normal Symfony solution. So the issue is confusing.

**Comment by picks44** [comment]
How can we translate the routing then ? I'm confused with this command http://jmsyst.com/bundles/JMSI18nRoutingBundle/master/usage#translating-routes

**Comment by picks44** [comment]
@stof can yu help me understanding how I can translate my routes ? I'm lost here.

**Comment by picks44** [comment]
@stof up ?

**Comment by picks44** [comment]
Please make the documentation clearer.

**Comment by picks44** [comment]
https://github.com/schmittjoh/JMSI18nRoutingBundle/issues/149#issuecomment-151850868
