### ISSUE TITLE
Is this bundle dead

### ISSUE THREAD

**Issue by deguif** [schmittjoh/JMSI18nRoutingBundle#203]
This bundle seems to be dead as pull requests are not reviewed, and latest release is from december 2015.

@schmittjoh do you still have some time to maintain it?

**Comment by tompiard** [comment]
This bundle is still working great on Symfony 3.2, but it seems dead indeed. Did anyone find a replacement?

**Comment by schmittjoh** [comment]
I'm not using it right now. 

I'm happy to give someone access who wants to have a look at the compatibility pull-requests (this is the main concern AFAIU?).
