### ISSUE TITLE
addClassesToCompile is deprecated

### ISSUE THREAD

**Issue by MisatoTremor** [schmittjoh/JMSI18nRoutingBundle#206]
Used in JMSI18nRoutingBundle/DependencyInjection/JMSI18nRoutingExtension.php:49

BC compatible fix would be to enclose with if (\PHP_VERSION_ID < 70000) { ... }

**Comment by deguif** [comment]
Can be closed now, ping @acasademont

**Comment by acasademont** [comment]
Fixed in master and 2.0.1 release
