### ISSUE TITLE
Breaks with Symfony 4.2.8

### ISSUE THREAD

**Issue by TamasSzigeti** [schmittjoh/JMSI18nRoutingBundle#237]
This PR breaks JMSI18nRoutingBundle
https://github.com/symfony/symfony/pull/31023/files

`Fatal error: Access level to JMS\I18nRoutingBundle\Router\I18nRouter::$defaultLocale must be protected (as in class Symfony\Bundle\FrameworkBundle\Routing\Router) or weaker in vendor/jms/i18n-routing-bundle/JMS/I18nRoutingBundle/Router/I18nRouter.php on line 293`

**Comment by monro93** [comment]
This issue should be fixed in https://github.com/schmittjoh/JMSI18nRoutingBundle/pull/236

A workaround is to set the symfony/routing version to 4.2.7 in your composer.json:

`"symfony/routing": "4.2.7"`

**Comment by TamasSzigeti** [comment]
Thank you!
