### ISSUE TITLE
Fix symfony 5 deprecations

### ISSUE THREAD

**Issue by florianajir** [schmittjoh/JMSI18nRoutingBundle#242]
`User Deprecated: The default value of the "$secure" and "$samesite" arguments of "Symfony\Component\HttpFoundation\Cookie::__construct"'s constructor will respectively change from "false" to "null" and from "null" to "lax" in Symfony 5.0, you should define their values explicitly or use "Cookie::create()" instead`

from `JMS/I18nRoutingBundle/EventListener/CookieSettingListener.php:47`

**Comment by lightcoresystems** [comment]
Hi, i did some updates in PR #243 , waiting for merge :)

**Comment by denis1994** [comment]
I'm also waiting for an update to this package because this is the only package why I can't upgrade to Symfony 5

**Comment by acasademont** [comment]
Hi all! Sorry for the huge delay. I'll try to get this merged asap. But also, I think it's time to consider this package as obsolete, Symfony already includes a number of i18n features.

**Comment by acasademont** [comment]
Merged and a new 3.0.4 tag has been created. Thank you all!!
