### ISSUE TITLE
PHP8 Support

### ISSUE THREAD

**Issue by Wirone** [schmittjoh/JMSI18nRoutingBundle#245]
Current requirement is `php: ^7.1` and it is not possible to use PHP8 in projects using this bundle.

Thanks in advance for adding support for PHP8.

**Comment by gjuric** [comment]
Latest release (3.1.0) should work and this issue can be closed.

**Comment by Wirone** [comment]
Sorry for the late response but I want to confirm that 3.1 works with PHP8. Thank you!
